log_dir: /pub/afeeney/bubbleformer_logs
seed: 42

nodes: 1
devices: 1

max_epochs: 40
batch_size: 16
accumulate_grad_batches: 1

checkpoint_path:

use_wandb: False
wandb_tags:
  - time-window-5
  - poolboiling
  - AdamW-optimizer
defaults:
  - _self_
  - data_cfg: poolboiling64
  - model_cfg: neighbor_moe1
  - optim_cfg: adamw
  - scheduler_cfg: cosine_warmup