dataset: poolboiling64_op250
input_fields: ["dfun", "temperature", "velx", "vely"]
output_fields: ["dfun", "temperature", "velx", "vely"]
normalize: none
downsample_factor: 1
history_time_window: 5
future_time_window: 5
time_step: 1
start_time: 100
return_fluid_params: True

train_paths:
  # Include some FC-72 cases to prevent forgetting
  - /share/crsp/lab/amowli/share/BubbleML_2_downsampled64_bicubic/PoolBoiling-Subcooled-FC72-2D/Twall_92.hdf5
  - /share/crsp/lab/amowli/share/BubbleML_2_downsampled64_bicubic/PoolBoiling-Subcooled-FC72-2D/Twall_94.hdf5
  - /share/crsp/lab/amowli/share/BubbleML_2_downsampled64_bicubic/PoolBoiling-Subcooled-FC72-2D/Twall_96.hdf5
  - /share/crsp/lab/amowli/share/BubbleML_2_downsampled64_bicubic/PoolBoiling-Subcooled-FC72-2D/Twall_98.hdf5
  - /share/crsp/lab/amowli/share/BubbleML_2_downsampled64_bicubic/PoolBoiling-Subcooled-FC72-2D/Twall_100.hdf5
  # Include some OP-250 cases
  - /share/crsp/lab/amowli/share/BubbleML_2_downsampled64_bicubic/PoolBoiling-Subcooled-OP250-2D/Twall_85.hdf5
  - /share/crsp/lab/amowli/share/BubbleML_2_downsampled64_bicubic/PoolBoiling-Subcooled-OP250-2D/Twall_89.hdf5
  - /share/crsp/lab/amowli/share/BubbleML_2_downsampled64_bicubic/PoolBoiling-Subcooled-OP250-2D/Twall_101.hdf5

val_paths:
  - /share/crsp/lab/amowli/share/BubbleML_2_downsampled64_bicubic/PoolBoiling-Subcooled-OP250-2D/Twall_81.hdf5

test_paths:
  - /share/crsp/lab/amowli/share/BubbleML_2_downsampled64_bicubic/PoolBoiling-Subcooled-OP250-2D/Twall_93.hdf5
  - /share/crsp/lab/amowli/share/BubbleML_2_downsampled64_bicubic/PoolBoiling-Subcooled-OP250-2D/Twall_97.hdf5