name: bubbleformer_film_vit
train_module_name: conditioned_forecast
params:
  patch_size: 16
  embed_dim: 768
  processor_blocks: 12
  num_heads: 12
  attn_scale: True
  feat_scale: True
  num_fluid_params: 16