name: vit_moe
train_module_name: moe_conditioned_forecast
params:
  patch_size: 4
  embed_dim: 192
  processor_blocks: 6
  num_heads: 6
  num_fluid_params: 13
  num_experts: 6
  topk: 2
  load_balance_loss_weight: 0.01